name: Unit Test

on: [push, pull_request]

jobs:
  teststalingrad:
    name: Stalingrad Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: pip install -e .
    - name: Test Variable
      run: python test/test_variable.py
    - name: Test Tensor
      run: python test/test_tensor.py
    - name: Test MNIST
      run: python test/test_mnist.py
